In [8]:
import numpy as np
import pandas as pd

# Scoring and Metrics

In [9]:
# pattern: positive => True, negative => False
df = pd.DataFrame([
    [15, True],
    [-2, False],
    [99, True],
    [-10, False],
    [8, True],
    [5, True],
    [-1000, False],
    [-1, False],
], columns=["x", "y"])
train, test = df.iloc[:4], df.iloc[4:]

In [10]:
train

x      y
0  15   True
1  -2  False
2  99   True
3 -10  False

In [11]:
test

x      y
4     8   True
5     5   True
6 -1000  False
7    -1  False

In [14]:
from sklearn.linear_model import LogisticRegression
# TODO: 
# 1. train a LogisticRegression on training data
# 2. score the model on the test data
model = LogisticRegression()
model.fit(train[["x"]], train["y"])
model.predict(test[["x"]])

array([ True, False, False, False])

In [16]:
model.score(test[["x"]], test["y"])   # by default, this uses accuracy_score

0.75

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(["A", "B"], ["A", "C"])

0.5

In [21]:
accuracy_score(test["y"], model.predict(test[["x"]]))

0.75

# Confusion Matrices

In [23]:
actual =    ["dog", "dog", "dog", "dog", "cat", "cat", "cat", "mouse", "mouse"]
predicted = ["dog", "dog", "dog", "cat", "cat", "dog", "cat", "mouse", "mouse"]

In [25]:
# ROW: an actual category
# COL: a prediction
confusion_matrix(actual, predicted)

array([[2, 1, 0],
       [1, 3, 0],
       [0, 0, 2]])

In [26]:
labels = ["dog", "cat", "mouse", "horse"]
cm = confusion_matrix(actual, predicted, labels=labels)
cm

array([[3, 1, 0, 0],
       [1, 2, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]])

In [29]:
pd.DataFrame(cm, index=labels, columns=labels)

dog  cat  mouse  horse
dog      3    1      0      0
cat      1    2      0      0
mouse    0    0      2      0
horse    0    0      0      0

# Multi-Class Metrics

In [7]:
actual =    ["dog", "dog", "dog", "dog", "cat", "cat", "cat", "cat", "mouse", "mouse"] * 199
predicted = ["dog", "dog", "dog", "dog", "cat", "dog", "cat", "dog", "mouse", "mouse"] * 199
actual += ["horse"] * 10
predicted += ["dog"] * 9 + ["horse"]

labels = ["dog", "cat", "mouse", "horse"]
cm = confusion_matrix(actual, predicted, labels=labels)
cm = pd.DataFrame(cm, index=labels, columns=labels)
cm

NameError: name 'confusion_matrix' is not defined

# Binary Classification Metrics

Unless otherwise specified, "precision" and "recall" refer to those metrics for the positive class when we're doing binary classification.

In [ ]:
actual = [False, True, True, True, True, False, False, True, True, True, True, True, True]
predicted = [False, True, True, True, True, True, True, False, False, False, True, True, True]
confusion_matrix(actual, predicted)